### ISSUE TITLE
findViewByClass is Private, can't acess it.

### ISSUE THREAD

**Issue by shkhaksar** [semsamot/ActionBarRTLizer#18]
ViewGroup homeView = (ViewGroup) rtlizer.findViewByClass("HomeView", actionBarView);

i can't acess this method. this is private and should be public. thank You

**Comment by waqqas-imena** [comment]
+1

**Comment by abbasalim** [comment]
سلام. من که کد رو دانلود کردم بعد به 
public
متد رو تغییر دادم و کار کرد

**Comment by hoseinit** [comment]
What if we use this code instead ?
`        ViewGroup homeView = (ViewGroup) rtlizer.getHomeView();
`
